### ISSUE TITLE
Stop exporting metrics

### ISSUE THREAD

**Issue by ashiddo11** [jmal98/sqs-exporter#2]
Hi, the exporter stopped working, can't see any sqs metrics getting scraped. Is this project still maintained?

**Comment by jmal98** [comment]
This project is still maintained.

Are there errors from the container that you can share?  Are the AWS credentials provided to it still valid?

**Comment by ashiddo11** [comment]
there are no logs, the credentials are valid as I dont see any credential provider error and I test it manually. Also I cant even see any sqs_ATTRIBUTE on the /metrics page

**Comment by jmal98** [comment]
Are there any queues visible to the credentials used?  I just pulled the docker image and tested it in an environment without queues and noticed that if the credentials are valid, but there are no SQS queues, there is no indication of this condition and the side-effect is that there are no sqs_x metrics available in the /metrics output.

**Comment by ashiddo11** [comment]
Yeah they have access to the sqs queues, its weird it was working a few weeks ago and then suddenly stopped. I'm pointing it to the right region using AWS_REGION env variable. Is there anything else I should try?

**Comment by ashiddo11** [comment]
any update?

**Comment by jmal98** [comment]
Which region are you using?  

Can you share a snippet of the logs?  i.e. docker logs <container id>

Also, can you confirm that with the same credentials and region, the aws cli list-queues command works?  i.e. aws sqs list-queues --region <region>

**Comment by ashiddo11** [comment]
using ap-southeast-1 (Singapore)

Logs:
```
2018-04-04 06:46:21.242:INFO::main: Logging initialized @14608ms
2018-04-04 06:46:21.735:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2018-04-04 06:46:22.040:INFO:oejs.AbstractConnector:main: Started ServerConnector@52845b96{HTTP/1.1,[http/1.1]}{0.0.0.0:9384}
2018-04-04 06:46:22.130:INFO:oejs.Server:main: Started @15496ms
04 Apr 2018 06:46:22,140 org.jmal98.sqs.exporter.Application:51 Exporter has started.
```
CLI:
```
aws sqs list-queues --region ap-southeast-1 | wc -l
22
```
The credentials work fine, Is the exporter working for you? Previously if I dont specify a region it goes to us-east-1 by default and I have one queue that I'd see on prometheus. Now I don't even see that anymore

I created a sqs exporter in golang and it works fine with my credentials (https://github.com/ashiddo11/sqs-exporter)

**Comment by jmal98** [comment]
I see the issue.  By the exporter's use of the aws sdk's defaults, if the region used isn't supported, it defaults to us-east-1.  I just confirmed that with a different queue created in ap-southeast-1, the exporter still only showed queue information from us-east-1.  

I suspect that this explains the behaviour observed on your end.

**Comment by ashiddo11** [comment]
Hi, tested the new release and works fine. Thanks :)
