### ISSUE TITLE
Exporter discovery problem

### ISSUE THREAD

**Issue by stafot** [jmal98/sqs-exporter#8]
I created a deployment for this sqs-exporter using the container as instructed here. It  seems that this exporter not get's discovered from my prometheus. Are there any clues to investigate why? 

Thanks, in advance.

**Comment by jmal98** [comment]
Can you share the snippet of your Prometheus configuration related to the exporter config?

**Comment by stafot** [comment]
@jmal98 sorry for left it opened. It is resolved a long ago. Thanks for your response though.
